## NAME RUPESH KUMAR
## REG.NO:-12528055
## ROLL NO. :- 61
## SECTION :- D2534

In [ ]:
# 1. from sk learn dataset import load_iris
# 2. convert num target to categorical label
# 3. create a new categoricl column called petal_size_category
# 4. check and handel null value, chk handel dublicate, chk handel outliers
# 5. apply label encoading on species column
# 6. apply one odd encoading on petal size categorical column
# 7. separate x and y
# 8. train test and split
# 9. do feature scaling using standard scaler

In [42]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [10]:
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data['target'] = iris.target

In [11]:
data.info

<bound method DataFrame.info of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 5 columns]>

In [12]:
species_map = {0: 'class1', 1: 'class2', 2: 'class3'}
data['species'] = data['target'].map(species_map)

In [13]:
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,class1
1,4.9,3.0,1.4,0.2,0,class1
2,4.7,3.2,1.3,0.2,0,class1
3,4.6,3.1,1.5,0.2,0,class1
4,5.0,3.6,1.4,0.2,0,class1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,class3
146,6.3,2.5,5.0,1.9,2,class3
147,6.5,3.0,5.2,2.0,2,class3
148,6.2,3.4,5.4,2.3,2,class3
149,5.9,3.0,5.1,1.8,2,class3

In [17]:
print(data['petal length (cm)'].min())
print(data['petal length (cm)'].max())

1.0
6.9

In [18]:
data['petal_size_category'] = pd.cut(data['petal length (cm)'],bins=[0, 2.5, 5, 7],labels=['small', 'medium', 'large'])

In [19]:
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species,petal_size_category
0,5.1,3.5,1.4,0.2,0,class1,small
1,4.9,3.0,1.4,0.2,0,class1,small
2,4.7,3.2,1.3,0.2,0,class1,small
3,4.6,3.1,1.5,0.2,0,class1,small
4,5.0,3.6,1.4,0.2,0,class1,small
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,class3,large
146,6.3,2.5,5.0,1.9,2,class3,medium
147,6.5,3.0,5.2,2.0,2,class3,large
148,6.2,3.4,5.4,2.3,2,class3,large
149,5.9,3.0,5.1,1.8,2,class3,large

In [20]:
data.isnull().sum()

sepal length (cm)      0
sepal width (cm)       0
petal length (cm)      0
petal width (cm)       0
target                 0
species                0
petal_size_category    0
dtype: int64

In [26]:
data.duplicated().sum()

np.int64(1)

In [27]:
data.drop_duplicates()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species,petal_size_category
0,5.1,3.5,1.4,0.2,0,class1,small
1,4.9,3.0,1.4,0.2,0,class1,small
2,4.7,3.2,1.3,0.2,0,class1,small
3,4.6,3.1,1.5,0.2,0,class1,small
4,5.0,3.6,1.4,0.2,0,class1,small
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,class3,large
146,6.3,2.5,5.0,1.9,2,class3,medium
147,6.5,3.0,5.2,2.0,2,class3,large
148,6.2,3.4,5.4,2.3,2,class3,large
149,5.9,3.0,5.1,1.8,2,class3,large

In [30]:
data.duplicated().sum().sum()

np.int64(1)

In [34]:
nums_cols=data.select_dtypes(np.number)
for num in nums_cols:
    q1=data[num].quantile(0.25)
    q3=data[num].quantile(0.75)
    iqr=q3-q1
    ul=q3+(1.5*iqr)
    ll=q1-(1.5*iqr)
    outliers=data[(data[num]<ll) | (data[num]>ul)]
    print(f'The number of Outlier is {num}:{len(outliers)}')
    data=data[(data[num]>=ll) & (data[num]<=ul)]

The number of Outlier is sepal length (cm):0
The number of Outlier is sepal width (cm):4
The number of Outlier is petal length (cm):0
The number of Outlier is petal width (cm):0
The number of Outlier is target:0

In [35]:
nums_cols=data.select_dtypes(np.number)
for num in nums_cols:
    q1=data[num].quantile(0.25)
    q3=data[num].quantile(0.75)
    iqr=q3-q1
    ul=q3+(1.5*iqr)
    ll=q1-(1.5*iqr)
    outliers=data[(data[num]<ll) | (data[num]>ul)]
    print(f'The number of Outlier is {num}:{len(outliers)}')
    data=data[(data[num]>=ll) & (data[num]<=ul)]

The number of Outlier is sepal length (cm):0
The number of Outlier is sepal width (cm):0
The number of Outlier is petal length (cm):0
The number of Outlier is petal width (cm):0
The number of Outlier is target:0

In [36]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['species']=le.fit_transform(data['species'])

In [37]:
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species,petal_size_category
0,5.1,3.5,1.4,0.2,0,0,small
1,4.9,3.0,1.4,0.2,0,0,small
2,4.7,3.2,1.3,0.2,0,0,small
3,4.6,3.1,1.5,0.2,0,0,small
4,5.0,3.6,1.4,0.2,0,0,small
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,2,large
146,6.3,2.5,5.0,1.9,2,2,medium
147,6.5,3.0,5.2,2.0,2,2,large
148,6.2,3.4,5.4,2.3,2,2,large
149,5.9,3.0,5.1,1.8,2,2,large

In [40]:
X = data[['target']]
y = data['species']

In [43]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [ ]:
mean = X_train.mean()
std = X_train.std()
X_train = (X_train - mean) / std
X_test = (X_test - mean) / std 
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)