In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# Load the dataset
data=sns.load_dataset('titanic')

In [4]:
# check the null value is present or not
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
# Fill all null value with mean of age using SimpleInputer class.
from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy='mean')
data['age']=imp.fit_transform(data[['age']])

In [7]:
data['age'].isnull().sum()

np.int64(0)

In [8]:
# Drop unwanted data
data.drop(['deck','sibsp','parch','who','adult_male','alone','class'],axis=1)

     survived  pclass     sex        age     fare embarked  embark_town alive
0           0       3    male  22.000000   7.2500        S  Southampton    no
1           1       1  female  38.000000  71.2833        C    Cherbourg   yes
2           1       3  female  26.000000   7.9250        S  Southampton   yes
3           1       1  female  35.000000  53.1000        S  Southampton   yes
4           0       3    male  35.000000   8.0500        S  Southampton    no
..        ...     ...     ...        ...      ...      ...          ...   ...
886         0       2    male  27.000000  13.0000        S  Southampton    no
887         1       1  female  19.000000  30.0000        S  Southampton   yes
888         0       3  female  29.699118  23.4500        S  Southampton    no
889         1       1    male  26.000000  30.0000        C    Cherbourg   yes
890         0       3    male  32.000000   7.7500        Q   Queenstown    no

[891 rows x 8 columns]

In [9]:
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
# Convert categorial data in numeric help of LableEncoder class.
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['alive']=le.fit_transform(data['alive'])
data['sex']=le.fit_transform(data['sex'])

In [11]:
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,0,False
1,1,1,0,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,1,False
2,1,3,0,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,1,True
3,1,1,0,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,1,False
4,0,3,1,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,0,True
887,1,1,0,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,1,True
888,0,3,0,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,0,False
889,1,1,1,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,1,True
890,0,3,1,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,0,True

In [12]:
data.drop(['embarked'],axis=1,inplace=True)

In [13]:
data

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.000000,1,0,7.2500,Third,man,True,NaN,Southampton,0,False
1,1,1,0,38.000000,1,0,71.2833,First,woman,False,C,Cherbourg,1,False
2,1,3,0,26.000000,0,0,7.9250,Third,woman,False,NaN,Southampton,1,True
3,1,1,0,35.000000,1,0,53.1000,First,woman,False,C,Southampton,1,False
4,0,3,1,35.000000,0,0,8.0500,Third,man,True,NaN,Southampton,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,Second,man,True,NaN,Southampton,0,True
887,1,1,0,19.000000,0,0,30.0000,First,woman,False,B,Southampton,1,True
888,0,3,0,29.699118,1,2,23.4500,Third,woman,False,NaN,Southampton,0,False
889,1,1,1,26.000000,0,0,30.0000,First,man,True,C,Cherbourg,1,True
890,0,3,1,32.000000,0,0,7.7500,Third,man,True,NaN,Queenstown,0,True

In [14]:
num_types=data.select_dtypes(include=np.number)
for num in num_types:
    q1=data[num].quantile(0.25)
    q3=data[num].quantile(0.75)
    iqr=q3-q1
    l1=q1-1.5*iqr
    r1=q3+1.5*iqr
    outlier=data[(data[num]<l1)|(data[num]>r1)].index

In [15]:
outlier

Index([], dtype='int64')